%RUNFORCDEMOLANGEVIN Run a FORC study of an equilibrium Langevin particle.
%
%   The resulting family is reversible: every reversal curve lies on the
%   same Langevin relation, so its FORC distribution should be zero apart
%   from numerical fitting and boundary effects.

Hmax = 1.0;
Hmin = -1.0;
NumPoints = 201;
Stride = 5;
MeasurementStride = [];
HrMin = -Inf;
HrMax = Inf;

Ms = 1.0;
Alpha = 4.0;
BiasField = 0.0;
SmoothingFactor = 2;

OutputFile = fullfile(fileparts(mfilename("fullpath")), ...
    "forc_demo_langevin_output.json");

solveFcn = @(H,Hmax,Hmin,state) simulateLangevin(H,Hmax,Hmin,state, ...
    "Ms",Ms,"Alpha",Alpha,"BiasField",BiasField);

sim = FORCSimulation(Hmax,Hmin, ...
    "NumPoints",NumPoints, ...
    "Stride",Stride, ...
    "MeasurementStride",MeasurementStride, ...
    "HrMin",HrMin, ...
    "HrMax",HrMax, ...
    "SolveFcn",solveFcn, ...
    "Verbose",true);
sim.run();
dist = sim.distribution(SmoothingFactor);

results.parameters = struct( ...
    "Hmax",Hmax, ...
    "Hmin",Hmin, ...
    "numPoints",NumPoints, ...
    "stride",Stride, ...
    "HrMin",HrMin, ...
    "HrMax",HrMax, ...
    "smoothingFactor",SmoothingFactor, ...
    "Ms",Ms, ...
    "Alpha",Alpha, ...
    "BiasField",BiasField);
results.majorBranch = struct("H",sim.HMajor,"M",sim.MMajor);
results.diagram = struct("Hr",sim.Hr,"H",sim.H,"M",sim.M);
results.distribution = struct("Hr",dist.Hr,"H",dist.H,"rho",dist.rho, ...
    "SmoothingFactor",dist.SmoothingFactor);

fileID = fopen(OutputFile,"w");
if fileID < 0
    error("runFORCDemoLangevin:CannotWrite", ...
        "Could not open %s for writing.",OutputFile);
end
closeFile = onCleanup(@() fclose(fileID));
fprintf(fileID,"%s",jsonencode(results));

fprintf("Wrote %s\n",OutputFile);
